package vn.edu.donga.unischedule.simulation;

import java.nio.ByteBuffer;
import java.security.MessageDigest;
import java.sql.*;
import java.time.LocalDate;
import java.util.*;
import static vn.edu.donga.unischedule.simulation.SimulationData.*;

/** INSERT-only import. Real keys are generated by MySQL and every FK is remapped. */
public final class HistoricalSeedImporter {
    public static final String MARKER="SEED_HISTORY_5Y_V1";
    static final Set<String> SHARED=Set.of("roles","departments","time_slots");
    public record Result(boolean inserted,Map<String,Long> counts,Map<String,String> originals) { }
    private HistoricalSeedImporter() { }
    public static boolean alreadyApplied(Connection c) throws SQLException {
        return scalar(c,"SELECT COUNT(*) FROM audit_logs WHERE action='"+MARKER+"'")>0;
    }
    public static Result apply(Connection c,SimulationData data,LocalDate asOf,long seed) throws Exception {
        String lock="history_seed_"+c.getCatalog();
        try(var p=c.prepareStatement("SELECT GET_LOCK(?,15)")) {p.setString(1,lock);try(var r=p.executeQuery()){r.next();if(r.getInt(1)!=1)throw new SQLException("Seed is already running");}}
        try {
            c.setAutoCommit(false);
            try {
                // Same lock used by the application's schedule transactions.
                try(var p=c.prepareStatement("SELECT id FROM roles WHERE code='ACADEMIC' FOR UPDATE");var r=p.executeQuery()){while(r.next()) { /* hold */ }}
                if(alreadyApplied(c)) {c.rollback();return new Result(false,Map.of(),Map.of());}
                if(scalar(c,"SELECT COUNT(*) FROM users WHERE username LIKE 'hist5\\_%' OR username='qt_hethong'")>0 || scalar(c,"SELECT COUNT(*) FROM classrooms WHERE code LIKE 'HS5-%'")>0)
                    throw new IllegalStateException("Historical seed identifiers already exist without a completion marker; refusing to mix datasets");
                var maxima=new LinkedHashMap<String,Long>(); var fingerprints=new LinkedHashMap<String,String>();
                for(String table:TABLES) maxima.put(table,scalar(c,"SELECT COALESCE(MAX("+(table.equals("user_roles")?"user_id":"id")+"),0) FROM `"+table+"`"));
                for(String table:TABLES) fingerprints.put(table,fingerprint(c,table,maxima.get(table)));
                var ids=new HashMap<String,Map<Integer,Long>>();
                var added=new LinkedHashMap<String,Long>();
                var importOrder=new ArrayList<>(TABLES);importOrder.remove("audit_logs");importOrder.add("audit_logs");
                for(String table:importOrder) {
                    ids.put(table,new HashMap<>());
                    if(SHARED.contains(table)) {
                        for(var row:data.rows(table)) {
                            String col=table.equals("time_slots")?"sort_order":"code";
                            try(var p=c.prepareStatement("SELECT id FROM `"+table+"` WHERE `"+col+"`=?")) {
                                p.setObject(1,row.get(col)); try(var r=p.executeQuery()){if(!r.next())throw new SQLException("Missing shared catalog "+table+" "+row.get(col));ids.get(table).put(n(row,"id"),r.getLong(1));}
                            }
                        }
                        added.put(table,0L);continue;
                    }
                    Map<String,String> foreign=new HashMap<>();
                    try(var r=c.getMetaData().getImportedKeys(c.getCatalog(),null,table)) {while(r.next())foreign.put(r.getString("FKCOLUMN_NAME"),r.getString("PKTABLE_NAME"));}
                    // Cache prepared statements by column shape; optional fields vary by row.
                    Map<String,PreparedStatement> statements=new HashMap<>();
                    try {
                        for(var original:data.rows(table)) {
                            var row=new LinkedHashMap<>(original);row.remove("id");
                            for(var fk:foreign.entrySet()) if(row.get(fk.getKey())!=null) row.put(fk.getKey(),mapped(ids,fk.getValue(),((Number)row.get(fk.getKey())).intValue()));
                            if(table.equals("notifications")&&row.get("reference_id")!=null) row.put("reference_id",mapped(ids,s(row,"reference_type"),n(original,"reference_id")));
                            if(table.equals("audit_logs")&&row.get("entity_id")!=null) row.put("entity_id",mapped(ids,s(row,"entity_type"),n(original,"entity_id")));
                            String columns=String.join("`,`",row.keySet());
                            var p=statements.get(columns);
                            if(p==null) {
                                p=c.prepareStatement("INSERT INTO `"+table+"` (`"+columns+"`) VALUES ("+String.join(",",Collections.nCopies(row.size(),"?"))+")",Statement.RETURN_GENERATED_KEYS);
                                statements.put(columns,p);
                            }
                            int i=1;for(Object value:row.values())p.setObject(i++,value);p.executeUpdate();
                            if(original.containsKey("id"))try(var keys=p.getGeneratedKeys()){if(!keys.next())throw new SQLException("Missing generated key");ids.get(table).put(n(original,"id"),keys.getLong(1));}
                        }
                    } finally {for(var p:statements.values())p.close();}
                    added.put(table,(long)data.rows(table).size());
                }
                // Native aggregate check on inserted sections, before committing.
                long mismatches=scalar(c,"SELECT COUNT(*) FROM course_sections cs WHERE cs.id>"+maxima.get("course_sections")+" AND cs.student_count<>(SELECT COUNT(*) FROM student_enrollments e WHERE e.course_section_id=cs.id AND e.status='ACTIVE')");
                if(mismatches!=0)throw new IllegalStateException("Student counts changed during import");
                for(String table:TABLES) if(!fingerprint(c,table,maxima.get(table)).equals(fingerprints.get(table))) throw new IllegalStateException("Existing rows changed: "+table+"; rolling back");
                String details=SimulationExport.json(row("seed",seed,"as_of",asOf.toString(),"kind","SYNTHETIC_HISTORY","added",added,"original_rows_sha256",fingerprints));
                try(var p=c.prepareStatement("INSERT INTO audit_logs(user_id,action,entity_type,details,created_at) VALUES (?,?,'database',?,?)")) {
                    p.setLong(1,mapped(ids,"users",1));p.setString(2,MARKER);p.setString(3,details);p.setString(4,asOf+" 12:00:00");p.executeUpdate();
                }
                c.commit();added.compute("audit_logs",(k,v)->v+1);
                return new Result(true,added,fingerprints);
            } catch(Exception ex) {c.rollback();throw ex;}
        } finally {
            try(var p=c.prepareStatement("SELECT RELEASE_LOCK(?)")){p.setString(1,lock);p.execute();}
            c.setAutoCommit(true);
        }
    }
    private static long mapped(Map<String,Map<Integer,Long>> maps,String table,int id) {
        Long value=maps.getOrDefault(table,Map.of()).get(id);
        if(value==null)throw new IllegalStateException("Unresolved reference "+table+"/"+id);return value;
    }
    static long scalar(Connection c,String sql) throws SQLException {try(var p=c.prepareStatement(sql);var r=p.executeQuery()){r.next();return r.getLong(1);}}
    private static String fingerprint(Connection c,String table,long max) throws Exception {
        MessageDigest digest=MessageDigest.getInstance("SHA-256");String key=table.equals("user_roles")?"user_id":"id";
        try(var p=c.prepareStatement("SELECT * FROM `"+table+"` WHERE `"+key+"`<=? ORDER BY "+(table.equals("user_roles")?"user_id,role_id":"id"))) {
            p.setLong(1,max);try(var r=p.executeQuery()) {while(r.next())for(int i=1;i<=r.getMetaData().getColumnCount();i++) {
                byte[] value=r.getBytes(i);digest.update(ByteBuffer.allocate(4).putInt(value==null?-1:value.length).array());if(value!=null)digest.update(value);
            }}
        }
        return HexFormat.of().formatHex(digest.digest());
    }
}
